"""add import staging tables

Revision ID: 3a7c8dea1004
Revises: b9a0ae06a010
Create Date: 2026-06-13 03:40:43.430379
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a7c8dea1004'
down_revision: str | None = 'b9a0ae06a010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('sheet_name', sa.String(length=120), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.BigInteger(), nullable=False),
    sa.Column('job_rows', sa.BigInteger(), nullable=False),
    sa.Column('divider_rows', sa.BigInteger(), nullable=False),
    sa.Column('blank_rows', sa.BigInteger(), nullable=False),
    sa.Column('ambiguous_rows', sa.BigInteger(), nullable=False),
    sa.Column('issue_count', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_import_batches_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    op.create_index(op.f('ix_import_batches_deleted_at'), 'import_batches', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_import_batches_file_sha256'), 'import_batches', ['file_sha256'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_table('import_rows',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_row_index', sa.BigInteger(), nullable=False),
    sa.Column('row_class', sa.String(length=20), nullable=False),
    sa.Column('legacy_reference', sa.String(length=64), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('committed_customer_id', sa.Integer(), nullable=True),
    sa.Column('committed_job_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['committed_customer_id'], ['customers.id'], name=op.f('fk_import_rows_committed_customer_id_customers')),
    sa.ForeignKeyConstraint(['committed_job_id'], ['jobs.id'], name=op.f('fk_import_rows_committed_job_id_jobs')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_import_rows_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows'))
    )
    op.create_index(op.f('ix_import_rows_batch_id'), 'import_rows', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_rows_legacy_reference'), 'import_rows', ['legacy_reference'], unique=False)
    op.create_index(op.f('ix_import_rows_review_status'), 'import_rows', ['review_status'], unique=False)
    op.create_index(op.f('ix_import_rows_row_class'), 'import_rows', ['row_class'], unique=False)
    op.create_table('import_issues',
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_issues_batch_id_import_batches')),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_import_issues_resolved_by_id_users')),
    sa.ForeignKeyConstraint(['row_id'], ['import_rows.id'], name=op.f('fk_import_issues_row_id_import_rows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_issues'))
    )
    op.create_index(op.f('ix_import_issues_batch_id'), 'import_issues', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_issues_kind'), 'import_issues', ['kind'], unique=False)
    op.create_index(op.f('ix_import_issues_row_id'), 'import_issues', ['row_id'], unique=False)
    op.create_index(op.f('ix_import_issues_severity'), 'import_issues', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_issues_severity'), table_name='import_issues')
    op.drop_index(op.f('ix_import_issues_row_id'), table_name='import_issues')
    op.drop_index(op.f('ix_import_issues_kind'), table_name='import_issues')
    op.drop_index(op.f('ix_import_issues_batch_id'), table_name='import_issues')
    op.drop_table('import_issues')
    op.drop_index(op.f('ix_import_rows_row_class'), table_name='import_rows')
    op.drop_index(op.f('ix_import_rows_review_status'), table_name='import_rows')
    op.drop_index(op.f('ix_import_rows_legacy_reference'), table_name='import_rows')
    op.drop_index(op.f('ix_import_rows_batch_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_file_sha256'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_deleted_at'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
