"""add import review audit columns

Revision ID: 7e512cf78bf7
Revises: 3a7c8dea1004
Create Date: 2026-06-13 04:13:37.644473
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e512cf78bf7'
down_revision: str | None = '3a7c8dea1004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_issues', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('import_rows', sa.Column('original_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('import_rows', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_rows', 'reviewed_at')
    op.drop_column('import_rows', 'original_parsed')
    op.drop_column('import_issues', 'resolved_at')
    # ### end Alembic commands ###
