"""add jobs legacy_reference

Revision ID: 91a6e16b2a20
Revises: 7e512cf78bf7
Create Date: 2026-06-13 05:12:02.856739
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a6e16b2a20'
down_revision: str | None = '7e512cf78bf7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('legacy_reference', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_jobs_legacy_reference'), 'jobs', ['legacy_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_legacy_reference'), table_name='jobs')
    op.drop_column('jobs', 'legacy_reference')
    # ### end Alembic commands ###
